### ISSUE TITLE
Error: fork-ts-checker-webpack-plugin hooks are already in use

### ISSUE THREAD

**Issue by sweetim** [wagerfield/nuxt-typescript#15]
After I run `npm run dev`, whenever I saved a `.js` extension file, it will throw an error shown below

```
✖ error Error: fork-ts-checker-webpack-plugin hooks are already in use
  at ForkTsCheckerWebpackPlugin.registerCustomHooks (/mnt/d/workspace/timx-site/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:187:19)  at ForkTsCheckerWebpackPlugin.apply (/mnt/d/workspace/timx-site/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:100:22)
  at webpack (/mnt/d/workspace/timx-site/node_modules/webpack/lib/webpack.js:37:12)
  at compilers.compilersOptions.map (/mnt/d/workspace/timx-site/node_modules/nuxt-edge/dist/nuxt.js:3919:24)
  at Array.map (<anonymous>)
  at Builder.webpackBuild (/mnt/d/workspace/timx-site/node_modules/nuxt-edge/dist/nuxt.js:3918:39)
```

Is there anyway I can exclude `.js` file extension? or resolve this problem?

I am currently using

```
"nuxt-edge": "^2.0.0-25623921.73d1b9d",
"nuxt-typescript": "^0.11.0",
"typescript": "^3.0.3",
"ts-loader": "^5.1.1",
```

**Comment by hartmut-co-uk** [comment]
@sweetim as far as I'm aware nuxt-edge wasn't supported yet as the module author was waiting for the stable nuxt2 release (which happened 2 days ago) - pls have a look at / keep track of https://github.com/wagerfield/nuxt-typescript/issues/3

**Comment by wagerfield** [comment]
@hartmut-co-uk, @sweetim I will be updating this module over the coming days to support Nuxt 2.0—stay tuned 🎉

**Comment by ktiedt** [comment]
Following this as it appears to be a problem we're hitting as well.

**Comment by CosmicPangolin** [comment]
@wagerfield Also following...any update by chance?

**Comment by hartmut-co-uk** [comment]
Hi, as a side note - there's a lot of movement on nuxt for better ts support and bringing @wagerfield's work into `create-nuxt-app` / as a nuxt core module
https://github.com/nuxt/create-nuxt-app/issues/23#issuecomment-442576246
https://github.com/nuxt/nuxt.js/pull/4164
where this repo `wagerfield/nuxt-typescript` has been repeatedly mentioned/suggested as a reference

**Comment by ktiedt** [comment]
Sadly this has caused us to second guess using Nuxt and moved back to just using the Vue cli where TS easily integrates without any fuss.
